from django.conf.urls import url
from django.views.generic import TemplateView

from flamingo import views

urlpatterns = [
    url(r'^org/search/', TemplateView.as_view(template_name='flamingo/organisations/org_search.html'),
        name='org-search'),
    url(r'^org/list/', views.OrgList.as_view(), name='org-list'),
    url(r'^org/(?P<pk>[0-9]+)/details/edit/', views.EditDetails.as_view(), name='org-details-edit'),
    url(r'^org/(?P<pk>[0-9]+)/details/', views.OrgDetails.as_view(), name='org-details'),
    url(r'^org/(?P<pk>[0-9]+)/users/search/', views.OrgUserSearch.as_view(), name='org-users-search'),
    url(r'^org/(?P<pk>[0-9]+)/users/list/', views.OrgUserList.as_view(), name='org-users-list'),
    url(r'^org/(?P<pk>[0-9]+)/members/add/', views.add_member, name='org-members-add'),
    url(r'^org/(?P<pk>[0-9]+)/members/', views.OrgMembers.as_view(), name='org-members'),
    url(r'^org/(?P<pk>[0-9]+)/member/(?P<member_pk>[0-9]+)/edit/', views.edit_member, name='org-member-edit'),
    url(r'^org/(?P<org_id>[0-9]+)/member/(?P<user_id>[0-9]+)/link/', views.link_user,
        name='org-member-link'),
    url(r'^org/(?P<org_id>[0-9]+)/member/(?P<member_id>[0-9]+)/delete/', views.UnlinkMember.as_view(),
        name='org-member-unlink'),
    url(r'^org/(?P<pk>[0-9]+)/member/(?P<member_pk>[0-9]+)/', views.MemberDetails.as_view(), name='org-member'),
    url(r'^org/(?P<pk>[0-9]+)/requirement/add/', views.add_requirement,
        name='org-requirement-add'),
    url(r'^org/(?P<pk>[0-9]+)/requirements/', views.OrgRequirements.as_view(),
        name='org-requirements'),
    url(r'^org/(?P<pk>[0-9]+)/requirement/(?P<requirement_pk>[0-9]+)/edit/', views.edit_requirement,
        name='org-requirement-edit'),
    url(r'^org/(?P<pk>[0-9]+)/requirement/(?P<requirement_pk>[0-9]+)/delete/', views.DeleteRequirement.as_view(),
        name='org-requirement-delete'),
    url(r'^org/(?P<pk>[0-9]+)/requirement/(?P<requirement_pk>[0-9]+)/', views.ViewRequirement.as_view(),
        name='org-requirement'),
    url(r'^org/(?P<pk>[0-9]+)/role/add/', views.add_role, name="org-role-add"),
    url(r'^org/(?P<pk>[0-9]+)/role/(?P<role_pk>[0-9]+)/edit/', views.edit_role, name="org-role-edit"),
    url(r'^org/(?P<pk>[0-9]+)/role/(?P<role_pk>[0-9]+)/delete/', views.DeleteRole.as_view(),
        name="org-role-delete"),
    url(r'^org/(?P<pk>[0-9]+)/role/(?P<role_pk>[0-9]+)/', views.ViewRole.as_view(), name="org-role"),
    url(r'^org/(?P<pk>[0-9]+)/roles/', views.ListRoles.as_view(), name="org-roles"),
    url(r'^user/search/', TemplateView.as_view(template_name='flamingo/users/user_search.html'),
        name='user-search'),
    url(r'^user/list/', views.UserList.as_view(), name='user-list'),
    url(r'^user/(?P<pk>[0-9]+)/details/documents/(?P<document_pk>[0-9]+)/edit/', views.UserEditDocuments.as_view(),
        name='user-documents-edit'),
    url(r'^user/(?P<pk>[0-9]+)/details/documents/', views.UserDocuments.as_view(),
        name='user-documents'),
    url(r'^user/(?P<pk>[0-9]+)/details/edit/', views.UserEditDetails.as_view(), name='user-details-edit'),
    url(r'^user/(?P<pk>[0-9]+)/details/', views.UserDetails.as_view(), name='user-details'),
    url(r'^curriculums/search/', TemplateView.as_view(template_name='flamingo/curriculums/curriculums_search.html'),
        name='curriculums-search'),
    url(r'^curriculums/list/', views.CurriculumList.as_view(), name='curriculums-list'),
    url(r'^curriculums/add/', views.CurriculumAdd.as_view(), name='curriculums-add'),
    url(r'^curriculums/(?P<pk>[0-9]+)/', views.CurriculumDetails.as_view(), name='curriculums-details'),
    url(r'^courses/search/', TemplateView.as_view(template_name='flamingo/courses/courses_search.html'),
        name='courses-search'),
    url(r'^courses/list/', views.CourseList.as_view(), name='courses-list'),
    url(r'^courses/add/', views.CourseAdd.as_view(), name='courses-add'),
    url(r'^courses/(?P<course_pk>[0-9]+)/edit/', views.CourseEdit.as_view(), name='courses-edit'),
    url(r'^providers/search/', TemplateView.as_view(template_name='flamingo/providers/providers_search.html'),
        name='providers-search'),
    url(r'^providers/list/', views.ProviderList.as_view(), name='providers-list'),
    url(r'^providers/add/', views.ProviderAdd.as_view(), name='providers-add'),
    url(r'^providers/(?P<provider_pk>[0-9]+)/edit/', views.ProviderEdit.as_view(), name='providers-edit'),
]
